apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-suite-test-component-git-source-pynx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-suite-test-component-git-source-pynx
    app.kubernetes.io/part-of: integ-app-wjxg
  name: integration-suite-test-component-git-source-pynx
  namespace: integration-e2e-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: integration-suite-test-component-git-source-pynx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: integration-suite-test-component-git-source-pynx
    spec:
      containers:
      - image: quay.io/dheerajodha/test-images:d2b87525a26544dc862f4f131dcc096e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
